/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 black_ferrari_488_gtb.glb
Author: RodyYassen (https://sketchfab.com/RodyYassen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-ferrari-488-gtb-e4d3246a89274efb9bb59068cad033f7
Title: Black Ferrari 488 GTB
*/

import React, { useRef } from 'react'
import {Decal, Dodecahedron, PerspectiveCamera, RenderTexture, useGLTF, Text,} from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/black_ferrari_488_gtb.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.08, 0.18, -0.06]} rotation={[-Math.PI / 2, 0, -0.48]} scale={1.48}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.17, 0, -0.13]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.disc_plate} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.rims} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.rims} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.rims} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.disc} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.disc} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_15.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_19.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_23.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_26.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_27.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_29.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_30.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_31.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_32.geometry} material={materials.Tire} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_34.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_35.geometry} material={materials['Material.004']} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_41.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_42.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_43.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_44.geometry} material={materials.Material}>
              <Decal position={[0, 1.2, 0.75]} rotation={0.3} scale={[3, 3, 3]}>
                <meshStandardMaterial roughness={0.6} transparent polygonOffset polygonOffsetFactor={-10}>
                  <RenderTexture attach="map" anisotropy={16}>
                    {/*мб убрать данную строчку?*/}
                    <PerspectiveCamera makeDefault manual aspect={0.9 / 0.25} position={[0, 0, 5]} />
                    <color attach="background" args={['#af2040']} />
                    <ambientLight intensity={0.5} />
                    <directionalLight position={[10, 10, 5]} />
                    <Text rotation={[0, Math.PI, 0]}  fontSize={4} color="white">
                      hello from drei
                    </Text>
                    <Dodecahedron />
                  </RenderTexture>
                </meshStandardMaterial>
              </Decal>
            </mesh>
            <mesh geometry={nodes.Object_45.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_46.geometry} material={materials.LED_Blue} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_54.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_55.geometry} material={materials['Material.004']} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_57.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_58.geometry} material={materials.LED_Blue} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_60.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_61.geometry} material={materials['Material.005']} />
          </group>
          <group position={[0.17, 0, -0.13]} rotation={[0.34, 0, 0]}>
            <mesh geometry={nodes.Object_69.geometry} material={materials.Grill} />
            <mesh geometry={nodes.Object_70.geometry} material={materials.Grill} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_72.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_73.geometry} material={materials['Led.001']} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_75.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_76.geometry} material={materials['Led.001']} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_80.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_81.geometry} material={materials.LED_Blue} />
          </group>
          <mesh geometry={nodes.Object_37.geometry} material={materials['Material.003']} position={[0.17, 0, -0.13]} rotation={[Math.PI / 2, 0, 0]} scale={0.1} />
          <mesh geometry={nodes.Object_39.geometry} material={materials['Material.003']} position={[0.17, 0, -0.13]} />
          <mesh geometry={nodes.Object_48.geometry} material={materials['Material.003']} position={[0.17, 0, -0.13]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.Window} position={[0.17, 0, -0.13]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials['Material.003']} position={[0.17, 0, -0.13]} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.Grill} position={[0.17, 0, -0.13]} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.LED_Blue} position={[0.17, 0.41, -0.13]} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.Grill} position={[0.17, 0, -0.13]} rotation={[0.15, 0, 0]} />
          <mesh geometry={nodes.Object_78.geometry} material={materials['Material.002']} position={[0.17, 0.41, -0.13]} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.Material} position={[0.17, 0.41, -0.13]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/black_ferrari_488_gtb.glb')
