// /* eslint-disable react/no-unknown-property */
// 'use client'
// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.13 ferrari_min.glb
// */
//
// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
//
// export function Model(props) {
//   const { nodes, materials } = useGLTF('/ferrari_min.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.08, 0, -0.22]} rotation={[-Math.PI / 2, 0, -0.477]} scale={1.476}>
//         <group rotation={[Math.PI / 2, 0, 0]}>
//           <group position={[0.165, 0, -0.133]} rotation={[0, 0, -Math.PI / 2]}>
//             <mesh geometry={nodes.Object_10.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_11.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_12.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_13.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_14.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_15.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_16.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_17.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_18.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_19.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_20.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_21.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_22.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_23.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_24.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_25.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_26.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_27.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_28.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_29.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_30.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_31.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_32.geometry} material={materials.Tire} />
//             <mesh geometry={nodes.Object_4.geometry} material={materials.disc_plate} />
//             <mesh geometry={nodes.Object_5.geometry} material={materials.rims} />
//             <mesh geometry={nodes.Object_6.geometry} material={materials.rims} />
//             <mesh geometry={nodes.Object_7.geometry} material={materials.rims} />
//             <mesh geometry={nodes.Object_8.geometry} material={materials.disc} />
//             <mesh geometry={nodes.Object_9.geometry} material={materials.disc} />
//           </group>
//           <group position={[0.165, 0, -0.133]} rotation={[0.337, 0, 0]}>
//             <mesh geometry={nodes.Object_69.geometry} material={materials.Grill} />
//             <mesh geometry={nodes.Object_70.geometry} material={materials.Grill} />
//           </group>
//           <group position={[0.165, 0, -0.133]}>
//             <mesh geometry={nodes.Object_57.geometry} material={materials['Material.001']} />
//             <mesh geometry={nodes.Object_58.geometry} material={materials.LED_Blue} />
//           </group>
//           <group position={[0.165, 0, -0.133]}>
//             <mesh geometry={nodes.Object_72.geometry} material={materials.material} />
//             <mesh geometry={nodes.Object_73.geometry} material={materials['Led.001']} />
//           </group>
//           <group position={[0.165, 0, -0.133]}>
//             <mesh geometry={nodes.Object_75.geometry} material={materials.material} />
//             <mesh geometry={nodes.Object_76.geometry} material={materials['Led.001']} />
//           </group>
//           <group position={[0.165, 0, -0.133]}>
//             <mesh geometry={nodes.Object_34.geometry} material={materials['Material.003']} />
//             <mesh geometry={nodes.Object_35.geometry} material={materials['Material.004']} />
//           </group>
//           <group position={[0.165, 0, -0.133]}>
//             <mesh geometry={nodes.Object_60.geometry} material={materials['Material.001']} />
//             <mesh geometry={nodes.Object_61.geometry} material={materials['Material.005']} />
//           </group>
//           <group position={[0.165, 0, -0.133]}>
//             <mesh geometry={nodes.Object_41.geometry} material={materials['Material.001']} />
//             <mesh geometry={nodes.Object_42.geometry} material={materials['Material.001']} />
//             <mesh geometry={nodes.Object_43.geometry} material={materials['Material.001']} />
//             <mesh geometry={nodes.Object_44.geometry} material={materials['Material.001']} />
//             <mesh geometry={nodes.Object_45.geometry} material={materials['Material.001']} />
//             <mesh geometry={nodes.Object_46.geometry} material={materials.LED_Blue} />
//           </group>
//           <group position={[0.165, 0, -0.133]}>
//             <mesh geometry={nodes.Object_54.geometry} material={materials['Material.003']} />
//             <mesh geometry={nodes.Object_55.geometry} material={materials['Material.004']} />
//           </group>
//           <group position={[0.165, 0, -0.133]}>
//             <mesh geometry={nodes.Object_80.geometry} material={materials['Material.003']} />
//             <mesh geometry={nodes.Object_81.geometry} material={materials.LED_Blue} />
//           </group>
//           <mesh geometry={nodes.Object_67.geometry} material={materials.Grill} position={[0.165, 0, -0.133]} rotation={[0.145, 0, 0]} />
//           <mesh geometry={nodes.Object_65.geometry} material={materials.LED_Blue} position={[0.165, 0.407, -0.133]} />
//           <mesh geometry={nodes.Object_37.geometry} material={materials['Material.003']} position={[0.165, 0, -0.133]} rotation={[Math.PI / 2, 0, 0]} scale={0.102} />
//           <mesh geometry={nodes.Object_78.geometry} material={materials['Material.002']} position={[0.165, 0.407, -0.133]} />
//           <mesh geometry={nodes.Object_63.geometry} material={materials.Grill} position={[0.165, 0, -0.133]} />
//           <mesh geometry={nodes.Object_39.geometry} material={materials['Material.003']} position={[0.165, 0, -0.133]} />
//           <mesh geometry={nodes.Object_52.geometry} material={materials['Material.003']} position={[0.165, 0, -0.133]} />
//           <mesh geometry={nodes.Object_48.geometry} material={materials['Material.003']} position={[0.165, 0, -0.133]} />
//           <mesh geometry={nodes.Object_50.geometry} material={materials.Window} position={[0.165, 0, -0.133]} />
//           <mesh geometry={nodes.Object_83.geometry} material={materials['Material.001']} position={[0.165, 0.407, -0.133]} />
//         </group>
//       </group>
//     </group>
//   )
// }
//
// useGLTF.preload('/ferrari_min.glb')
