/* eslint-disable react/no-unknown-property */
// @ts-nocheck
/* eslint-disable react-hooks/exhaustive-deps */
'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 black_ferrari_488_gtb.glb
Author: RodyYassen (https://sketchfab.com/RodyYassen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-ferrari-488-gtb-e4d3246a89274efb9bb59068cad033f7
Title: Black Ferrari 488 GTB
*/

import React, {useMemo, useRef} from 'react'
import {Decal, Dodecahedron, PerspectiveCamera, RenderTexture, useGLTF, Text,} from '@react-three/drei'
import {applyProps} from "@react-three/fiber";

export function Ferarri_old(props) {
  // rc={`https://better-autumn.pockethost.io/api/files/${project.collectionId}/${project.id}/${project.main_image}`}
  const { nodes, materials } = useGLTF('https://better-autumn.pockethost.io/api/files/threeDCar/4xuefn1yvzj1e0q/ferrari_min_GRNqq2IWpi.glb')
  useMemo(()=>{
    Object.values(nodes).forEach((node) => node.isMesh && (node.receiveShadow = node.castShadow = true))
    applyProps(materials.Material, {color: "gray", envMapIntensity: 4, roughness: 0.5, metalness: 1 })
  })
  return (
    <group {...props} dispose={null}>
      {/* eslint-disable-next react/no-unknown-property */}
      <group position={[0, 0, -0.06]} rotation={[-Math.PI / 2, 0, -0.48]} scale={1.48}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.17, 0, -0.13]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.disc_plate} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.rims} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.rims} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.rims} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.disc} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.disc} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Tire}  />
            <mesh geometry={nodes.Object_12.geometry} material={materials.Tire}  />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_15.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_19.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_23.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_26.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_27.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_29.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_30.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_31.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_32.geometry} material={materials.Tire} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_34.geometry} material={materials['Material.003']}  />
            <mesh geometry={nodes.Object_35.geometry} material={materials['Material.004']}  />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_41.geometry} material={materials.Material}  >
              <Decal position={[1.4, 0.8, 0.3]} rotation={-0.3} scale={[0.5, 0.2, 2]}>
                <meshStandardMaterial roughness={0.9} transparent polygonOffset polygonOffsetFactor={-10}>
                  <RenderTexture attach="map" anisotropy={16}>
                    {/*мб убрать данную строчку?*/}
                    <PerspectiveCamera makeDefault manual aspect={0.9 / 0.25} position={[0, 0, 6]} />
                    {/*красный фон*/}
                    <color attach="background" args={['#af2040']} />
                    <ambientLight intensity={0.5} />
                    <directionalLight position={[10, 10, 5]} />
                    <Text rotation={[0, Math.PI, 0]}  fontSize={4} color="white">
                      hip wrap
                    </Text>
                    {/*<Dodecahedron />*/}
                  </RenderTexture>
                </meshStandardMaterial>
              </Decal>
            </mesh>
            <mesh geometry={nodes.Object_42.geometry} material={materials.Material}/>
            <mesh geometry={nodes.Object_43.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_44.geometry} material={materials.Material} >
              <Decal position={[-1, 0.75, 0.8]} rotation={0.6} scale={[0.5, 0.2, 2]}>
                <meshStandardMaterial roughness={0.9} transparent polygonOffset polygonOffsetFactor={-10}>
                  <RenderTexture attach="map" anisotropy={16}>
                    {/*мб убрать данную строчку?*/}
                    <PerspectiveCamera makeDefault manual aspect={0.9 / 0.25} position={[0, 0, 6]} />
                    {/*красный фон*/}
                    <color attach="background" args={['#af2040']} />
                    <ambientLight intensity={0.5} />
                    <directionalLight position={[10, 10, 5]} />
                    <Text rotation={[0, Math.PI, 0]}  fontSize={2} color="white">
                      hip wrap
                    </Text>
                    {/*точка хз зачем) */}
                    {/*<Dodecahedron />*/}
                  </RenderTexture>
                </meshStandardMaterial>
              </Decal>
              {/*[ , высота, */}

            </mesh>
            <mesh geometry={nodes.Object_45.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_46.geometry} material={materials.LED_Blue} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_54.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_55.geometry} material={materials['Material.004']} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_57.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_58.geometry} material={materials.LED_Blue} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_60.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_61.geometry} material={materials['Material.005']} />
          </group>
          <group position={[0.17, 0, -0.13]} rotation={[0.34, 0, 0]}>
            <mesh geometry={nodes.Object_69.geometry} material={materials.Grill} />
            <mesh geometry={nodes.Object_70.geometry} material={materials.Grill} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_72.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_73.geometry} material={materials['Led.001']} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_75.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_76.geometry} material={materials['Led.001']} />
          </group>
          <group position={[0.17, 0, -0.13]}>
            <mesh geometry={nodes.Object_80.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_81.geometry} material={materials.LED_Blue} />
          </group>
          <mesh geometry={nodes.Object_37.geometry} material={materials['Material.003']} position={[0.17, 0, -0.13]} rotation={[Math.PI / 2, 0, 0]} scale={0.1} />
          <mesh geometry={nodes.Object_39.geometry} material={materials['Material.003']} position={[0.17, 0, -0.13]} />
          <mesh geometry={nodes.Object_48.geometry} material={materials['Material.003']} position={[0.17, 0, -0.13]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.Window} position={[0.17, 0, -0.13]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials['Material.003']} position={[0.17, 0, -0.13]} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.Grill} position={[0.17, 0, -0.13]} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.LED_Blue} position={[0.17, 0.41, -0.13]} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.Grill} position={[0.17, 0, -0.13]} rotation={[0.15, 0, 0]} />
          <mesh geometry={nodes.Object_78.geometry} material={materials['Material.002']} position={[0.17, 0.41, -0.13]} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.Material} position={[0.17, 0.41, -0.13]} />
        </group>
      </group>
    </group>
  )
}

// useGLTF.preload('/black_ferrari_488_gtb.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ferrari_min.glb
*/


export function Ferarri(props) {
   let { nodes, materials } = useGLTF('https://better-autumn.pockethost.io/api/files/threeDCar/4xuefn1yvzj1e0q/ferrari_min_GRNqq2IWpi.glb')

  useMemo(()=>{
    Object.values(nodes).forEach((node) => node.isMesh && (node.receiveShadow = node.castShadow = true))
    applyProps(materials['Material.001'], {color: props.color, envMapIntensity: 4, roughness: 0.5, metalness: 1 })
    applyProps(materials.LED_Blue, {color: "red" })

  })
  return (
      <group {...props} dispose={null}>
        <group position={[-0.08, 0, -0.22]} rotation={[-Math.PI / 2, 0, -0.477]} scale={1.476}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0.165, 0, -0.133]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Object_10.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_11.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_12.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_13.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_14.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_15.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_16.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_17.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_18.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_19.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_20.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_21.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_22.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_23.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_24.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_25.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_26.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_27.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_28.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_29.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_30.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_31.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_32.geometry} material={materials.Tire} />
              <mesh geometry={nodes.Object_4.geometry} material={materials.disc_plate} />
              <mesh geometry={nodes.Object_5.geometry} material={materials.rims} />
              <mesh geometry={nodes.Object_6.geometry} material={materials.rims} />
              <mesh geometry={nodes.Object_7.geometry} material={materials.rims} />
              <mesh geometry={nodes.Object_8.geometry} material={materials.disc} />
              <mesh geometry={nodes.Object_9.geometry} material={materials.disc} />
            </group>
            <group position={[0.165, 0, -0.133]} rotation={[0.337, 0, 0]}>
              <mesh geometry={nodes.Object_69.geometry} material={materials.Grill} />
              <mesh geometry={nodes.Object_70.geometry} material={materials.Grill} />
            </group>
            <group position={[0.165, 0, -0.133]}>
              <mesh geometry={nodes.Object_57.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_58.geometry} material={materials.LED_Blue} />
            </group>
            <group position={[0.165, 0, -0.133]}>
              <mesh geometry={nodes.Object_72.geometry} material={materials.material} />
              <mesh geometry={nodes.Object_73.geometry} material={materials['Led.001']} />
            </group>
            <group position={[0.165, 0, -0.133]}>
              <mesh geometry={nodes.Object_75.geometry} material={materials.material} />
              <mesh geometry={nodes.Object_76.geometry} material={materials['Led.001']} />
            </group>
            <group position={[0.165, 0, -0.133]}>
              <mesh geometry={nodes.Object_34.geometry} material={materials['Material.003']} />
              <mesh geometry={nodes.Object_35.geometry} material={materials['Material.004']} />
            </group>
            <group position={[0.165, 0, -0.133]}>
              <mesh geometry={nodes.Object_60.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_61.geometry} material={materials['Material.005']} />
            </group>
            <group position={[0.165, 0, -0.133]}>
              <mesh geometry={nodes.Object_41.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_42.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_43.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_44.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_45.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_46.geometry} material={materials.LED_Blue} />
            </group>
            <group position={[0.165, 0, -0.133]}>
              <mesh geometry={nodes.Object_54.geometry} material={materials['Material.003']} />
              <mesh geometry={nodes.Object_55.geometry} material={materials['Material.004']} />
            </group>
            <group position={[0.165, 0, -0.133]}>
              <mesh geometry={nodes.Object_80.geometry} material={materials['Material.003']} />
              <mesh geometry={nodes.Object_81.geometry} material={materials.LED_Blue} />
            </group>
            <mesh geometry={nodes.Object_67.geometry} material={materials.Grill} position={[0.165, 0, -0.133]} rotation={[0.145, 0, 0]} />
            <mesh geometry={nodes.Object_65.geometry} material={materials.LED_Blue} position={[0.165, 0.407, -0.133]} />
            <mesh geometry={nodes.Object_37.geometry} material={materials['Material.003']} position={[0.165, 0, -0.133]} rotation={[Math.PI / 2, 0, 0]} scale={0.102} />
            <mesh geometry={nodes.Object_78.geometry} material={materials['Material.002']} position={[0.165, 0.407, -0.133]} />
            <mesh geometry={nodes.Object_63.geometry} material={materials.Grill} position={[0.165, 0, -0.133]} />
            <mesh geometry={nodes.Object_39.geometry} material={materials['Material.003']} position={[0.165, 0, -0.133]} />
            <mesh geometry={nodes.Object_52.geometry} material={materials['Material.003']} position={[0.165, 0, -0.133]} />
            <mesh geometry={nodes.Object_48.geometry} material={materials['Material.003']} position={[0.165, 0, -0.133]} />
            <mesh geometry={nodes.Object_50.geometry} material={materials.Window} position={[0.165, 0, -0.133]} />
            <mesh geometry={nodes.Object_83.geometry} material={materials['Material.001']} position={[0.165, 0.407, -0.133]} />
          </group>
        </group>
      </group>
  )
}

useGLTF.preload('https://better-autumn.pockethost.io/api/files/threeDCar/4xuefn1yvzj1e0q/ferrari_min_GRNqq2IWpi.glb')

