'use client'
import {Box} from "@chakra-ui/react";
import Head from "next/head";
import React, { Suspense } from "react";
import FilterButton from "../components/filterButton";
import Grids from "../components/grids";
import styles from "../styles/Home.module.css";
import {pb} from "../utils/pb";
import { CarThree } from "../components/threeDCar";

export default function Home(props) {
  const [target, setTarget] = React.useState(0);
  console.log("target ", target);
  console.log("data index: ", props.posts.data[target].name);

  return (
    <div className={styles.container}>
      <Head>
        <title>HIPWRAP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="public/favicon.ico" />
      </Head>
      <main>
        <Box w="100%" h="50vh">
          <Suspense fallback={<p>loading...</p>}>
             <CarThree></CarThree>
          </Suspense>
        </Box>

        <FilterButton func={setTarget} data={props.posts.data}></FilterButton>
        {/* <Skeleton isLoaded={renderedPhoto} fadeDuration={4} startColor='pink.500' endColor='orange.500'  height='100px'> */}
        {/* {!renderedPhoto && <LoaderElement />} */}
        <Grids
          target={props.posts.data[target]}
        ></Grids>
        {/* <SuspenseComponent target={props.posts.data[target]}/> */}
        {/* </Skeleton> */}

      </main>
    </div>
  );
}

// запрос данных категорий для фильтра
export async function getStaticProps() {
  try {
    const getRecords = await pb?.collection("services").getFullList({
      sort: "-created",
    });
    // TODO по идее можно переделать без JSON
    const data = JSON.parse(JSON.stringify(getRecords));
    data.unshift({ id: 0, name: "все" });
    return {
      props: {
        // TODO упростить представление потом
        posts: { data },
      }, // will be passed to the page component as props
    };
  } catch (err) {
    console.log("err: ", err);
    return err;
  }
}


